name: "New Prod deployment"

# concurrency: 
#   group: prod-deployment
#   cancel-in-progress: true

on:
    push:
        branches:
            - 'main'

defaults:
  run:
    working-directory: ./dabs_job_template

jobs:
  prod:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle for Prod
        run: databricks bundle validate -t prod
      - name: Deploy Bundle to prod
        run: databricks bundle deploy -t prod
      - name: Run Bundle in prod
        run: databricks bundle run -t prod dabs_job_template_job --refresh-all
        env:
            DATABRICKS_TOKEN: ${{ secrets.PROD_SP_TOKEN }}
            DATABRICKS_BUNDLE_ENV: prod
